### PR TITLE
Include git reference in the template

### PR DESCRIPTION
**Pull request by mdellweg**
This may help to regenerate the CI on old branches if applying the latest is not an option.

### CODE REVIEW

**Comment by daviddavis** [comment]
This is a great idea 👍

**Comment by quba42** [comment]
I have been manually writing these into commit messages whenever I remembered to do so. This is better! :+1:

**Review by fao89 — APPROVED** [review]
🎉

**Comment by mdellweg** [comment]
This is covering the template_config, github and docs section. I no one asks for more places, i will merge on monday.

**Review by quba42 — APPROVED** [review]

**Pull request merged**
