### PR TITLE
Fix publish jobs by using app label

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #8311

### CODE REVIEW

**Review by fao89 — APPROVED** [review]
👏🏽

**Review by mdellweg — APPROVED** [review]
This looks right to me.
But i keep wondering, whether that change will imply that the client packages are named differently, or if there's some other unforseen side effect?

**Comment by daviddavis** [comment]
> But i keep wondering, whether that change will imply that the client packages are named differently, or if there's some other unforseen side effect?

It's possible but at least from my reading of the code, it looks like we'll continue to use the package name. For one, it looks like we use [the module name to filter the api spec](https://github.com/pulp/pulpcore/blob/28b875bcf2d24ff23c64275844d817dfb3d1a9dc/pulpcore/openapi/__init__.py#L373).

**Comment by daviddavis** [comment]
Oh but maybe module name != plugin name. That could be problematic?

**Comment by mdellweg** [comment]
Hmm. I may be OK. Let's try for one day.

**Comment by bmbouter** [comment]
Thank you for fixing this.

**Pull request merged**
