### PR TITLE
Fix commit message issue

### PR DESCRIPTION
**Pull request by fao89**
issue: https://github.com/pulp/plugin_template/actions/runs/463579136

### CODE REVIEW

**Comment by mdellweg** [comment]
What is this needed for?
Can we make the script not depend on GH-Actions?

**Comment by fao89** [comment]
> What is this needed for?
> Can we make the script not depend on GH-Actions?

passing through "Required PR" commit messages, and I think it is possible to make it not GHA dependent

**Review by mdellweg — APPROVED** [review]
If i understand correctly, this is to prevent using the required-PR mechanism for anything but pull requests.

**Comment by fao89** [comment]
> If i understand correctly, this is to prevent using the required-PR mechanism for anything but pull requests.

yes, that was the idea!

**Pull request merged**
