### PR TITLE
Adds PR processor github actions workflow

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #4365
https://pulp.plan.io/issues/4365

### CODE REVIEW

**Comment by dralley** [comment]
Only suggestion, maybe this job (and others like it) should run from the pulp-ci repo rather than this one.

**Comment by daviddavis** [comment]
Since this workflow is triggered by a repository event, I think it has to reside in the each repository's `.github/workflow`. If it were a scheduled job, then it could be moved to pulp-ci.

**Comment by bmbouter** [comment]
This is great! I'm +1 to merge and roll out to plugins and then remove the old one. Thank you @daviddavis !

**Comment by daviddavis** [comment]
Processing PRs on events didn't worked so now the PR processor is a scheduled job at pulp-ci.

**Pull request closed without merging**
