### PR TITLE
Use pip 2020 resolver

### PR DESCRIPTION
**Pull request by fao89**
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Is this a precaution, or do we have an issue this is supposed to solve?
(I realized it wasn't the solution for our latest installer CI failure)

**Comment by daviddavis** [comment]
I believe this sort of change should be documented in the changelog as well.

**Comment by fao89** [comment]
it is for matching with pulp-oci-images:
https://github.com/pulp/pulp-oci-images/blob/master/pulp_fedora31/Containerfile#L11

**Comment by mdellweg** [comment]
As far as i understand this activates a feature in preview state. Not sure we want this without a reason. OTOH maybe we want it to know we are compatible with the next version of pip.

**Pull request closed without merging**
