### PR TITLE
Fix the performance tests

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #7896

### CODE REVIEW

**Review by fao89 — APPROVED** [review]
this is great!

**Comment by daviddavis** [comment]
I made these changes against pulp_file (https://github.com/pulp/pulp_file/pull/453). If pulp_file's nightly workflow passes, we should merge this.

**Comment by daviddavis** [comment]
Looks like the pulp_file nightly job is passing. Merging.

CC @pulp/rpm

**Comment by fao89** [comment]
it was running functional tests, so I started these PRs:
https://github.com/pulp/plugin_template/pull/323
https://github.com/pulp/pulp_rpm/pull/1904
CC @pulp/rpm

**Pull request merged**
