### PR TITLE
Add a single commit check workflow

### PR DESCRIPTION
**Pull request by daviddavis**
[noissue]

### CODE REVIEW

**Comment by daviddavis** [comment]
Stolen from Katello: https://github.com/Katello/katello/blob/master/.github/workflows/pull_request.yml

I'm imagining that this will be a non-blocking test. In other words, it won't prevent merges. It will just help to warn contributors/PR reviewers that there's more than one commit.

**Comment by bmbouter** [comment]
Awesome! Will this be enabled by default or do plugins need to opt-in? I'm +1 to enabling by default and opting out, but I'm ok w/ whatever you decide.

**Comment by daviddavis** [comment]
Thanks I forgot to set a default. I'm imagining it'll be enabled by default too.

**Review by bmbouter — APPROVED** [review]
I kind of liked the discourse announcement part. :) Thanks for doing this!

**Comment by daviddavis** [comment]
> I kind of liked the discourse announcement part. :) Thanks for doing this!

Ha yea, that was a WIP I didn't mean to commit yet. Eventually I want to automatically have the release automation automatically post the announcement to discourse.

**Review by rochacbruno — APPROVED** [review]
Nice! I will set it to false on galaxy_ng on next ci update.

We allow multiple commits because we enforce Squash and Merge.

**Comment by quba42** [comment]
I think I will also opt out pulp_deb. The PR volume is not so high that I feel the need to enforce single commits via automation.

**Comment by mdellweg** [comment]
Can this check be used to set/delete a "multiple commit" label on the PR, instead of presenting a failed test?

**Comment by daviddavis** [comment]
I think we could if we used a `pull_request_target` workflow. I personally like having a failing job as it's more obvious and shows near the merge button. But if you think we ought to use a label instead, I'd say open an issue, we can discuss more and I can look into it.

**Pull request merged**
